Repository tasnimzotder/smart-snippets-and-emojis, pull requests merged in 2020-09, with the labels that each got.

#2 Update emoji-snippets.code-snippets
  snippets/emoji-snippets.code-snippets
Labels: enhancement

#3 v1.0.3
  CHANGELOG.md
  README.md
  package.json
Labels: documentation

#4 Update README.md
  README.md
Labels: documentation

#5 Updated README
  README.md
Labels: documentation

#6 v1.0.4
  CHANGELOG.md
  README.md
  icon.png
  icon_x.png
  images/icons/cpp.png
  images/icons/html.png
  images/icons/javascript.png
  images/icons/markdown.png
  images/icons/node-js.png
  images/icons/python.png
  package.json
  snippets/node-snippets.code-snippets
Labels: documentation, enhancement

#7 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation
